version: "3"
services:
  gatewayserivce:
    image: gatewayservice
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8082:80"
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "8083:80"
  pingservice:
    image: pingservice
    build:
      context: .
      dockerfile: PingService/Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - gatewayserivce
  pongservice:
    image: pongservice
    build:
      context: .
      dockerfile: PongService/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - gatewayserivce