# This is a generated file. Not intended for manual editing.
version: "3"
services:
  authservice:
    build:
      context: "/Users/patrickstolc/RiderProjects/APIGatewayExample"
      dockerfile: "AuthService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/AuthService.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "authservice:dev"
    ports: []
    volumes:
    - "/Users/patrickstolc/.nuget/packages:/root/.nuget/packages"
    - "/Users/patrickstolc/RiderProjects/APIGatewayExample/AuthService:/app:rw"
    - "/Users/patrickstolc/RiderProjects/APIGatewayExample:/src:rw"
    working_dir: "/app"
